/**:
  ros__parameters:
    ntrip:
      host: "ntrip.example.com"
      user_name: "-----------"
      password: "---------"
      mount_point: "VRSRTCM31"
      port: 2101
      use_nav_sat_fix_init: false
      nav_sat_fix_topic_name: "/fix"
      init_ntrip_location_lat: 0.0000000000
      init_ntrip_location_lon: 0.0000000000
      use_gpgga_for_ntrip: true
      gpgga_topic_name: "/gpgga"
      gpgga_interval_sec: 5.0

    serial_port:
      publish_port_rtcm: false
      name: "/dev/pts/3"
      baud_rate: 460800

    rtcm_publisher:
      publish_rtcm: false
      rtcm_topic: "/rtcm"
      rtcm_frame_id: "rtcm"